#pragma once

//#define DEBUG

enum class ErrorCode {
    SUCCESS = 0x00,
    ENV_LOCALAPPDATA_NOT_SET = 0x01,
    ENV_HOME_NOT_SET = 0x02,
    ENV_XDG_CONFIG_HOME_NOT_SET = 0x03,
    UNABLE_TO_CREATE_CONFIG_FILE = 0x04,
    WIN32_ERROR = 0x05,
    MISSING_PARAMS = 0x06,
    INVALID_PARAMS = 0x07,
    INVALID_CONNECTION_STRING = 0x08,
    INVALID_CA_STRING = 0x09,
    INVALID_DB_CONFIG = 0x0A,
    MYSQL_LIBRARY_INIT_ERROR = 0x0B,
    MYSQL_INIT_ERROR = 0x0C,
    MYSQL_SSL_SET_ERROR = 0x0D,
    MYSQL_REAL_CONNECTION_ERROR = 0x0E,
    MYSQL_QUERY_ERROR = 0x0F,
    MYSQL_STORE_RESULT_ERROR = 0x10,
    UNKNOWN_ERROR = 0xFF
};

void printError(ErrorCode err);